/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package damas;

import javax.swing.JButton;

/**
 *
 * @author cris_
 */

public class damas extends javax.swing.JFrame {

    private void iniciarTablero(JButton [][] tablero){
        tablero[0][1] = btn01;
        
        System.out.println(tablero[0][1].getText());
        

}

    
    JButton [][] tablero = new JButton[8][8];
    /**
     * Creates new form Principal2
     */
    
    public damas() {
        initComponents();
        iniciarTablero(tablero);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btn00 = new javax.swing.JButton();
        btn01 = new javax.swing.JButton();
        btn02 = new javax.swing.JButton();
        btn03 = new javax.swing.JButton();
        btn04 = new javax.swing.JButton();
        btn05 = new javax.swing.JButton();
        btn06 = new javax.swing.JButton();
        btn07 = new javax.swing.JButton();
        btn10 = new javax.swing.JButton();
        btn11 = new javax.swing.JButton();
        btn12 = new javax.swing.JButton();
        btn13 = new javax.swing.JButton();
        btn14 = new javax.swing.JButton();
        btn15 = new javax.swing.JButton();
        btn16 = new javax.swing.JButton();
        btn17 = new javax.swing.JButton();
        btn20 = new javax.swing.JButton();
        btn21 = new javax.swing.JButton();
        btn22 = new javax.swing.JButton();
        btn23 = new javax.swing.JButton();
        btn24 = new javax.swing.JButton();
        btn25 = new javax.swing.JButton();
        btn26 = new javax.swing.JButton();
        btn27 = new javax.swing.JButton();
        btn30 = new javax.swing.JButton();
        btn31 = new javax.swing.JButton();
        btn32 = new javax.swing.JButton();
        btn33 = new javax.swing.JButton();
        btn34 = new javax.swing.JButton();
        btn35 = new javax.swing.JButton();
        btn36 = new javax.swing.JButton();
        btn37 = new javax.swing.JButton();
        btn40 = new javax.swing.JButton();
        btn41 = new javax.swing.JButton();
        btn42 = new javax.swing.JButton();
        btn43 = new javax.swing.JButton();
        btn44 = new javax.swing.JButton();
        btn45 = new javax.swing.JButton();
        btn46 = new javax.swing.JButton();
        btn47 = new javax.swing.JButton();
        btn50 = new javax.swing.JButton();
        btn51 = new javax.swing.JButton();
        btn52 = new javax.swing.JButton();
        btn53 = new javax.swing.JButton();
        btn54 = new javax.swing.JButton();
        btn55 = new javax.swing.JButton();
        btn56 = new javax.swing.JButton();
        btn57 = new javax.swing.JButton();
        btn60 = new javax.swing.JButton();
        btn61 = new javax.swing.JButton();
        btn62 = new javax.swing.JButton();
        btn63 = new javax.swing.JButton();
        btn64 = new javax.swing.JButton();
        btn65 = new javax.swing.JButton();
        btn66 = new javax.swing.JButton();
        btn67 = new javax.swing.JButton();
        btn70 = new javax.swing.JButton();
        btn71 = new javax.swing.JButton();
        btn72 = new javax.swing.JButton();
        btn73 = new javax.swing.JButton();
        btn74 = new javax.swing.JButton();
        btn75 = new javax.swing.JButton();
        btn76 = new javax.swing.JButton();
        btn77 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(510, 490));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel2.setLayout(new java.awt.GridLayout(8, 8));

        btn00.setBackground(new java.awt.Color(255, 255, 255));
        btn00.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        btn00.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn00);

        btn01.setBackground(new java.awt.Color(0, 0, 0));
        btn01.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        btn01.setForeground(new java.awt.Color(204, 0, 0));
        btn01.setText("*");
        jPanel2.add(btn01);

        btn02.setBackground(new java.awt.Color(255, 255, 255));
        btn02.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        btn02.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn02);

        btn03.setBackground(new java.awt.Color(0, 0, 0));
        btn03.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        btn03.setForeground(new java.awt.Color(204, 0, 0));
        btn03.setText("*");
        jPanel2.add(btn03);

        btn04.setBackground(new java.awt.Color(255, 255, 255));
        btn04.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        btn04.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn04);

        btn05.setBackground(new java.awt.Color(0, 0, 0));
        btn05.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        btn05.setForeground(new java.awt.Color(204, 0, 0));
        btn05.setText("*");
        jPanel2.add(btn05);

        btn06.setBackground(new java.awt.Color(255, 255, 255));
        btn06.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        btn06.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn06);

        btn07.setBackground(new java.awt.Color(0, 0, 0));
        btn07.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        btn07.setForeground(new java.awt.Color(204, 0, 0));
        btn07.setText("*");
        jPanel2.add(btn07);

        btn10.setBackground(new java.awt.Color(0, 0, 0));
        btn10.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        btn10.setForeground(new java.awt.Color(204, 0, 0));
        btn10.setText("*");
        jPanel2.add(btn10);

        btn11.setBackground(new java.awt.Color(255, 255, 255));
        btn11.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        btn11.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn11);

        btn12.setBackground(new java.awt.Color(0, 0, 0));
        btn12.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        btn12.setForeground(new java.awt.Color(204, 0, 0));
        btn12.setText("*");
        jPanel2.add(btn12);

        btn13.setBackground(new java.awt.Color(255, 255, 255));
        btn13.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        btn13.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn13);

        btn14.setBackground(new java.awt.Color(0, 0, 0));
        btn14.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        btn14.setForeground(new java.awt.Color(204, 0, 0));
        btn14.setText("*");
        jPanel2.add(btn14);

        btn15.setBackground(new java.awt.Color(255, 255, 255));
        btn15.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        btn15.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn15);

        btn16.setBackground(new java.awt.Color(0, 0, 0));
        btn16.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        btn16.setForeground(new java.awt.Color(204, 0, 0));
        btn16.setText("*");
        jPanel2.add(btn16);

        btn17.setBackground(new java.awt.Color(255, 255, 255));
        btn17.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        btn17.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn17);

        btn20.setBackground(new java.awt.Color(255, 255, 255));
        btn20.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        btn20.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn20);

        btn21.setBackground(new java.awt.Color(0, 0, 0));
        btn21.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        btn21.setForeground(new java.awt.Color(204, 0, 0));
        btn21.setText("*");
        jPanel2.add(btn21);

        btn22.setBackground(new java.awt.Color(255, 255, 255));
        btn22.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        btn22.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn22);

        btn23.setBackground(new java.awt.Color(0, 0, 0));
        btn23.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        btn23.setForeground(new java.awt.Color(204, 0, 0));
        btn23.setText("*");
        jPanel2.add(btn23);

        btn24.setBackground(new java.awt.Color(255, 255, 255));
        btn24.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        btn24.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn24);

        btn25.setBackground(new java.awt.Color(0, 0, 0));
        btn25.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        btn25.setForeground(new java.awt.Color(204, 0, 0));
        btn25.setText("*");
        jPanel2.add(btn25);

        btn26.setBackground(new java.awt.Color(255, 255, 255));
        btn26.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        btn26.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn26);

        btn27.setBackground(new java.awt.Color(0, 0, 0));
        btn27.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        btn27.setForeground(new java.awt.Color(204, 0, 0));
        btn27.setText("*");
        jPanel2.add(btn27);

        btn30.setBackground(new java.awt.Color(0, 0, 0));
        btn30.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        jPanel2.add(btn30);

        btn31.setBackground(new java.awt.Color(255, 255, 255));
        btn31.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        btn31.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn31);

        btn32.setBackground(new java.awt.Color(0, 0, 0));
        btn32.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        jPanel2.add(btn32);

        btn33.setBackground(new java.awt.Color(255, 255, 255));
        btn33.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        btn33.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn33);

        btn34.setBackground(new java.awt.Color(0, 0, 0));
        btn34.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        jPanel2.add(btn34);

        btn35.setBackground(new java.awt.Color(255, 255, 255));
        btn35.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        btn35.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn35);

        btn36.setBackground(new java.awt.Color(0, 0, 0));
        btn36.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        jPanel2.add(btn36);

        btn37.setBackground(new java.awt.Color(255, 255, 255));
        btn37.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        btn37.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn37);

        btn40.setBackground(new java.awt.Color(255, 255, 255));
        btn40.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        btn40.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn40);

        btn41.setBackground(new java.awt.Color(0, 0, 0));
        btn41.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        jPanel2.add(btn41);

        btn42.setBackground(new java.awt.Color(255, 255, 255));
        btn42.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        btn42.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn42);

        btn43.setBackground(new java.awt.Color(0, 0, 0));
        btn43.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        jPanel2.add(btn43);

        btn44.setBackground(new java.awt.Color(255, 255, 255));
        btn44.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        btn44.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn44);

        btn45.setBackground(new java.awt.Color(0, 0, 0));
        btn45.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        jPanel2.add(btn45);

        btn46.setBackground(new java.awt.Color(255, 255, 255));
        btn46.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        btn46.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn46);

        btn47.setBackground(new java.awt.Color(0, 0, 0));
        btn47.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        jPanel2.add(btn47);

        btn50.setBackground(new java.awt.Color(0, 0, 0));
        btn50.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        btn50.setForeground(new java.awt.Color(255, 255, 255));
        btn50.setText("O");
        jPanel2.add(btn50);

        btn51.setBackground(new java.awt.Color(255, 255, 255));
        btn51.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        btn51.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn51);

        btn52.setBackground(new java.awt.Color(0, 0, 0));
        btn52.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        btn52.setForeground(new java.awt.Color(255, 255, 255));
        btn52.setText("O");
        jPanel2.add(btn52);

        btn53.setBackground(new java.awt.Color(255, 255, 255));
        btn53.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        btn53.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn53);

        btn54.setBackground(new java.awt.Color(0, 0, 0));
        btn54.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        btn54.setForeground(new java.awt.Color(255, 255, 255));
        btn54.setText("O");
        jPanel2.add(btn54);

        btn55.setBackground(new java.awt.Color(255, 255, 255));
        btn55.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        btn55.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn55);

        btn56.setBackground(new java.awt.Color(0, 0, 0));
        btn56.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        btn56.setForeground(new java.awt.Color(255, 255, 255));
        btn56.setText("O");
        jPanel2.add(btn56);

        btn57.setBackground(new java.awt.Color(255, 255, 255));
        btn57.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        btn57.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(btn57);

        btn60.setBackground(new java.awt.Color(255, 255, 255));
        btn60.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        jPanel2.add(btn60);

        btn61.setBackground(new java.awt.Color(0, 0, 0));
        btn61.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        btn61.setForeground(new java.awt.Color(255, 255, 255));
        btn61.setText("O");
        jPanel2.add(btn61);

        btn62.setBackground(new java.awt.Color(255, 255, 255));
        btn62.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        jPanel2.add(btn62);

        btn63.setBackground(new java.awt.Color(0, 0, 0));
        btn63.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        btn63.setForeground(new java.awt.Color(255, 255, 255));
        btn63.setText("O");
        jPanel2.add(btn63);

        btn64.setBackground(new java.awt.Color(255, 255, 255));
        btn64.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        jPanel2.add(btn64);

        btn65.setBackground(new java.awt.Color(0, 0, 0));
        btn65.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        btn65.setForeground(new java.awt.Color(255, 255, 255));
        btn65.setText("O");
        jPanel2.add(btn65);

        btn66.setBackground(new java.awt.Color(255, 255, 255));
        btn66.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        jPanel2.add(btn66);

        btn67.setBackground(new java.awt.Color(0, 0, 0));
        btn67.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        btn67.setForeground(new java.awt.Color(255, 255, 255));
        btn67.setText("O");
        jPanel2.add(btn67);

        btn70.setBackground(new java.awt.Color(0, 0, 0));
        btn70.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        btn70.setForeground(new java.awt.Color(255, 255, 255));
        btn70.setText("O");
        jPanel2.add(btn70);

        btn71.setBackground(new java.awt.Color(255, 255, 255));
        btn71.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        jPanel2.add(btn71);

        btn72.setBackground(new java.awt.Color(0, 0, 0));
        btn72.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        btn72.setForeground(new java.awt.Color(255, 255, 255));
        btn72.setText("O");
        jPanel2.add(btn72);

        btn73.setBackground(new java.awt.Color(255, 255, 255));
        btn73.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        jPanel2.add(btn73);

        btn74.setBackground(new java.awt.Color(0, 0, 0));
        btn74.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        btn74.setForeground(new java.awt.Color(255, 255, 255));
        btn74.setText("O");
        jPanel2.add(btn74);

        btn75.setBackground(new java.awt.Color(255, 255, 255));
        btn75.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        jPanel2.add(btn75);

        btn76.setBackground(new java.awt.Color(0, 0, 0));
        btn76.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        btn76.setForeground(new java.awt.Color(255, 255, 255));
        btn76.setText("O");
        jPanel2.add(btn76);

        btn77.setBackground(new java.awt.Color(255, 255, 255));
        btn77.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        jPanel2.add(btn77);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(20, 20, 460, 400);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(damas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(damas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(damas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(damas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new damas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn00;
    private javax.swing.JButton btn01;
    private javax.swing.JButton btn02;
    private javax.swing.JButton btn03;
    private javax.swing.JButton btn04;
    private javax.swing.JButton btn05;
    private javax.swing.JButton btn06;
    private javax.swing.JButton btn07;
    private javax.swing.JButton btn10;
    private javax.swing.JButton btn11;
    private javax.swing.JButton btn12;
    private javax.swing.JButton btn13;
    private javax.swing.JButton btn14;
    private javax.swing.JButton btn15;
    private javax.swing.JButton btn16;
    private javax.swing.JButton btn17;
    private javax.swing.JButton btn20;
    private javax.swing.JButton btn21;
    private javax.swing.JButton btn22;
    private javax.swing.JButton btn23;
    private javax.swing.JButton btn24;
    private javax.swing.JButton btn25;
    private javax.swing.JButton btn26;
    private javax.swing.JButton btn27;
    private javax.swing.JButton btn30;
    private javax.swing.JButton btn31;
    private javax.swing.JButton btn32;
    private javax.swing.JButton btn33;
    private javax.swing.JButton btn34;
    private javax.swing.JButton btn35;
    private javax.swing.JButton btn36;
    private javax.swing.JButton btn37;
    private javax.swing.JButton btn40;
    private javax.swing.JButton btn41;
    private javax.swing.JButton btn42;
    private javax.swing.JButton btn43;
    private javax.swing.JButton btn44;
    private javax.swing.JButton btn45;
    private javax.swing.JButton btn46;
    private javax.swing.JButton btn47;
    private javax.swing.JButton btn50;
    private javax.swing.JButton btn51;
    private javax.swing.JButton btn52;
    private javax.swing.JButton btn53;
    private javax.swing.JButton btn54;
    private javax.swing.JButton btn55;
    private javax.swing.JButton btn56;
    private javax.swing.JButton btn57;
    private javax.swing.JButton btn60;
    private javax.swing.JButton btn61;
    private javax.swing.JButton btn62;
    private javax.swing.JButton btn63;
    private javax.swing.JButton btn64;
    private javax.swing.JButton btn65;
    private javax.swing.JButton btn66;
    private javax.swing.JButton btn67;
    private javax.swing.JButton btn70;
    private javax.swing.JButton btn71;
    private javax.swing.JButton btn72;
    private javax.swing.JButton btn73;
    private javax.swing.JButton btn74;
    private javax.swing.JButton btn75;
    private javax.swing.JButton btn76;
    private javax.swing.JButton btn77;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
